# EigenVault Operator Configuration

ethereum:
  rpc_url: "https://holesky.infura.io/v3/YOUR_PROJECT_ID"
  operator_address: "0x0000000000000000000000000000000000000000"
  private_key: "0x0000000000000000000000000000000000000000000000000000000000000000"
  service_manager_address: "0x1234567890123456789012345678901234567890"
  eigenvault_hook_address: "0x2345678901234567890123456789012345678901"
  order_vault_address: "0x3456789012345678901234567890123456789012"
  gas_limit: 500000
  gas_price: 20000000000  # 20 gwei
  confirmation_blocks: 3

matching:
  max_pending_orders: 1000
  matching_interval_ms: 100
  price_tolerance_bps: 10     # 0.1%
  max_slippage_bps: 50        # 0.5%
  order_timeout_seconds: 3600 # 1 hour
  enable_cross_pool_matching: true

networking:
  listen_port: 9000
  bootstrap_peers:
    - "127.0.0.1:9001"
    - "127.0.0.1:9002"
  min_peers: 3
  max_peers: 50
  connection_timeout_seconds: 30
  gossip_interval_ms: 1000
  enable_encryption: true

proofs:
  circuit_path: "./circuits/build"
  proving_key_path: "./circuits/build/order_matching_final.zkey"
  verification_key_path: "./circuits/build/order_matching_verification_key.json"
  max_proof_size: 1048576     # 1MB
  proof_timeout_seconds: 300  # 5 minutes
  enable_batch_proving: true