[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
libs = ["contracts/lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer_runs = 10000
via_ir = true
ffi = true

remappings = [
    "@eigenlayer/=contracts/lib/eigenlayer-contracts/src/contracts/",
    "@eigenlayer-middleware/=contracts/lib/eigenlayer-middleware/src/",
    "@uniswap/v4-core/=contracts/lib/v4-core/",
    "@uniswap/v4-periphery/=contracts/lib/v4-periphery/",
    "@openzeppelin/contracts/=contracts/lib/openzeppelin-contracts/contracts/",
    "@forge-std/=contracts/lib/forge-std/src/",

]

[rpc_endpoints]
unichain = "https://sepolia.unichain.org"
holesky = "https://ethereum-holesky-rpc.publicnode.com"